services:
  
  proxy:
    restart: always
    image: haproxy:2.2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

    ports:
      - 80:80
      - 443:443
      - 9000:9000

  proxy-checker:
    image: haproxy:2.2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

